name: unlearn_canvas
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - albumentations==0.4.3
    - datasets==2.8.0
    - diffusers
    - opencv-python==4.1.2.30
    - pudb==2019.2
    - invisible-watermark
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.36.0.dev0  # This is necessary for diffuser
    - torchmetrics==0.6.0
    - kornia==0.6
    - taming-transformers-rom1504
    - clip
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - openai
    - gradio
    - seaborn
    - git+https://github.com/crowsonkb/k-diffusion.git
    - loguru # This is for style transfer: Style_Drop
    - ml_collections # This is for style transfer: Style_Drop
    - webdataset # This is for style transfer: Style_Drop
    - ftfy # This is for style transfer: Style_Drop
    - yacs # This is for style transfer: MAST
    - controlnet_aux # This is for style transfer: BLIP
    - fvcore # This is for ICL_Inpainting
    - h5py # This is for ICL_Inpainting
    - xtcocotools # This is for ICL_Inpainting
    - natsort # This is for ICL_Inpainting
    - timm==0.3.2 # This is for ICL_Inpainting
    - git+https://github.com/cocodataset/panopticapi.git # This is for ICL_Inpainting
    - fairscale # This is for ICL_Inpainting
    - git+https://github.com/facebookresearch/detectron2.git # This is for ICL_Inpainting
    - open_clip_torch # This is for ICL_Prompt_Diffusion
